# Generated by Django 3.2.1 on 2024-06-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]